import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tripzy Travel App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.variable} antialiased
          relative min-h-screen
        `}
        style={{
          background:
            "linear-gradient(to bottom, #F5F8FF 0%, #DBF5FF 50%, #ffffff 50%, #ffffff 100%)",
        }}
      >
        {children}
      </body>
    </html>
  );
}
